### ISSUE TITLE
Use Benchmark instead of Time

### ISSUE THREAD

**Issue by Ana06** [r-obert/pry-larryify.rb#3]
First of all, I really like the idea of the gem. 👍 

Currently `Time.now` is used to measure. What about using the [Benchmark](http://ruby-doc.org/stdlib-2.5.0/libdoc/benchmark/rdoc/Benchmark.html) Ruby class? It gets you the CPU time, system CPU time, the sum of the user and system CPU times, and the elapsed real time. The elapsed real time is much accurate than what the gem is using. When trying this in my computer:

##### With Benchmark (time is just calling `Benchmark.measure`)
[23] pry(#<ProjectLogEntryTest>)> time {(1..100000000).to_a.map{ |a| a*3 }.sum }
  9.660000   0.460000  10.120000 ( 10.122338)
=> nil

##### With the gem
[24] pry(#<ProjectLogEntryTest>)> (1..100000000).to_a.map{ |a| a*3 }.sum
Benchmark: 18.20s=> 15000000150000000

-----

Also, with Benchmark I didn't have any problem, but with the gem my computer got stuck. I guess it is a memory problem, but I would have to take a more close look to be sure. 🤔

**Comment by r-obert** [comment]
I think using Benchmark isn't possible because it expects a block of Ruby code to evaluate where as pry-larryify uses a before/after hook approach. But if you found a solution that works then please send a PR :-)

**Comment by r-obert** [comment]
hey @Ana06 
i reworked how time is measured, maybe this issue is fixed.
can you take a look? gem name has changed, so `gem install pry-auto_benching.rb`.
cheers
